services:
  achievementladder:
    image: ${DOCKER_REGISTRY-}achievementladder
    container_name: achi-api
    build:
      context: .
      dockerfile: AchievementLadder/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  achievementladder.database:
    image: postgres:15
    container_name: achi-database
    environment:
      - POSTGRES_DB=achievementladder
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
