services:
  achievementladder:
    image: ${DOCKER_REGISTRY-}achievementladder
    container_name: achi-api
    build:
      context: .
      dockerfile: AchievementLadder/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  achievementladder.database:
    image: postgres:latest
    container_name: achi-database
    environment:
      - POSTGRES_DB=achievementladder
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
