services:
  achievementladder:
    image: ${DOCKER_REGISTRY-}achievementladder
    container_name: achi-api
    build:
      context: .
      dockerfile: AchievementLadder/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - achievementladder.database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Database=Host=achievementladder.database;Port=5432;Database=achievement;Username=postgres;Password=postgres

  achievementladder.database:
    image: postgres:15
    container_name: achi-database
    environment:
      - POSTGRES_DB=achievement
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

volumes:
  postgres-data:
